### ISSUE TITLE
Shops

### ISSUE THREAD

**Issue by LuchiiTTG** [orn8/tinfoil#76]

**Comment by LuchiiTTG** [comment]
Hey so sorry didn't mean to add an issue it was meant to save it no problems everything works flawlessly thanks for the quick response 🙏

**Comment by orn8** [comment]
No problem, glad you liked the project! If you want to help support this project in any way, starring the project would be very much appreciated.

If you have any more current issues, please feel free to inform me here. Otherwise, please close the issue as complete.
